# Generated by Django 2.2.13 on 2020-12-20 00:11

import bonds.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='isin',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(code='invalid_isin', message='ISIN must be an uppercase alphanumeric string', regex='^[A-Z0-9]*$'), bonds.models.validate_isin_length]),
        ),
        migrations.AlterField(
            model_name='bond',
            name='lei',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_lei', message='LEI must be an uppercase alphanumeric string', regex='^[A-Z0-9]*$'), bonds.models.validate_lei_length]),
        ),
    ]
